[package]
name = "asm-simulator"
version = "0.1.3"
authors = ["Kosuke Takahashi <kilotango37@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
regex = "1"
